### ISSUE TITLE
Replace "rclone ls" with "rclone lsf"?

### ISSUE THREAD

**Issue by wolfv6** [bcardiff/docker-rclone#3]
Not sure if this is an issue.

From line 14 in https://github.com/bcardiff/docker-rclone/blob/master/sync.sh:

    if test "$(rclone ls $SYNC_SRC $RCLONE_OPTS)"; then

"rclone lsf" is a new feature on rclone 1.40, and produces a smaller output than "rclone ls".
https://rclone.org/commands/rclone_lsf/  Would using "lsf" consume less bandwidth?

**Comment by guillaumelachaud** [comment]
I second this. I have MANY files on my gdrive account and the `rclone ls` takes a very long time. Having an option to bypass the check altogether would also be nice.

**Comment by pfidr34** [comment]
> Not sure if this is an issue.
> 
> From line 14 in https://github.com/bcardiff/docker-rclone/blob/master/sync.sh:
> 
> ```
> if test "$(rclone ls $SYNC_SRC $RCLONE_OPTS)"; then
> ```
> 
> "rclone lsf" is a new feature on rclone 1.40, and produces a smaller output than "rclone ls".
> https://rclone.org/commands/rclone_lsf/ Would using "lsf" consume less bandwidth?

Hi, I have updated this project to the most current version of rclone and added a ENV variable that will take ls or lsf

https://hub.docker.com/r/pfidr/rclone
https://github.com/pfidr34/docker-rclone

**Comment by pfidr34** [comment]
> I second this. I have MANY files on my gdrive account and the `rclone ls` takes a very long time. Having an option to bypass the check altogether would also be nice.

Hi, I have updated this project to the most current version of rclone and added a ENV variable that will allow you to skip this check.

https://hub.docker.com/r/pfidr/rclone
https://github.com/pfidr34/docker-rclone
